'use strict';

/**
 * Add raw_rows and split_rows columns to fuel_import_batches.
 * raw_rows = original file row count before splitting
 * split_rows = number of rows generated by multi-product splitting
 */

exports.up = async function (knex) {
  await knex.schema.alterTable('fuel_import_batches', (t) => {
    t.integer('raw_rows').nullable();
    t.integer('split_rows').notNullable().defaultTo(0);
  });
};

exports.down = async function (knex) {
  await knex.schema.alterTable('fuel_import_batches', (t) => {
    t.dropColumn('raw_rows');
    t.dropColumn('split_rows');
  });
};
